name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Validar estructura de Docker Compose
        run: docker compose config
        env:
          PORT: 9000
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_USER: ci
          DB_PASSWORD: ci
          DB_NAME: ci

      - name: Probar construcción de contenedores Docker
        run: docker compose build